Svdesu/ch372/new circuit complete page
Chronofit/chrono-android pull request #3
Opened 2021-08-04 00:50 UTC by SVD6

**Clubhouse Story:**
- https://app.clubhouse.io/chrono/story/372/new-circuit-complete-page

**What does this PR solve?**
- Got a new design for the circuit complete page paired with a pretty unique feature (the random fact).

**List the steps to take to replicate the behavior introduced by this PR**
- End of any circuit

**List any known issues that this PR brings about**
- None
- Unfortunately I wasn't able to randomize the cats that show up as the graphic. Some of the animations look corrupted. Not sure what the problem is but didn't have the time to look into it. We should try and solve this problem for the next update.

**What's something funny/stupid that happened when working on this story?**
- Fact API is jokes sometimes, hopefully there isn't anything seriously inappropriate.

**Other information**
- None

**Please check if the PR fulfills these requirements**
- [ ] The commit messages follows our guidelines
- [ ] All errors and warnings have been taken care of

2021-08-04 01:30 UTC, harigovind1998 requested changes

2021-08-04 01:30 UTC, harigovind1998 commented on app/src/main/java/ca/chronofit/chrono/circuit/CircuitTimerActivity.kt
> +                client.newCall(request).execute().use { response ->
Wrap this in a try catch. Seems like it is still something that can fail relatively easily compared to others. Infact, i would recommend getting rid of the if statement and use a try catch. If say for example the wifi crashes after the if statement but before the request/response is received, it can still crash.

2021-08-04 02:03 UTC, harigovind1998 commented on app/src/main/java/ca/chronofit/chrono/circuit/CircuitTimerActivity.kt
> +                client.newCall(request).execute().use { response ->
Actually still leave the if statement in.

2021-08-04 02:54 UTC, harigovind1998 reviewed
Are there any animations that you know work? For now make that one default. When testing, I see that the displayed animation looks corrupt.

2021-08-06 01:30 UTC, SVD6 commented on app/src/main/java/ca/chronofit/chrono/circuit/CircuitTimerActivity.kt
> +                client.newCall(request).execute().use { response ->
Donezo

2021-08-06 01:40 UTC, harigovind1998 approved these changes

2021-08-06 01:40 UTC, harigovind1998 commented
Approved. Have not tested with no internet access.

2021-08-06 02:04 UTC, merged